### ISSUE TITLE
unexpected very negative affinity score

### ISSUE THREAD

**Issue by gkxiao** [dptech-corp/Uni-Dock#10]
There is a known Vinda scoring bug in the current undock (see: [unexpected very negative affinity score](https://github.com/ccsb-scripps/AutoDock-Vina/issues/68#top)  ).
<p>Here is an example:</p>
<pre line="1" lang="python">
MODEL 1
REMARK VINA RESULT:  -357.833      0.000      0.000
REMARK INTER + INTRA:          18.065
REMARK INTER:                  -1.981
REMARK INTRA:                  20.046
REMARK UNBOUND:               585.088
REMARK  Name = ZINC00442390
REMARK SMILES COC(=O)c1c(NC(=O)c2cnccn2)sc2c1CCCCCC2
REMARK SMILES IDX 19 1 18 2 5 3 6 4 16 5 17 6 3 7 4 8 2 9 1 10 7 11 8 12 9 14
REMARK SMILES IDX 10 15 15 16 11 17 14 18 12 19 13 20 24 21 23 22 20 24 21 25
REMARK SMILES IDX 22 26
REMARK H PARENT 7 13
REMARK Flexibility Score: 90.00
ROOT
ATOM      1  C   UNL     1      -9.305  79.565  84.302  1.00  0.00     0.037 C
ENDROOT
BRANCH   1   2
ATOM      2  C   UNL     1      -9.015  79.737  82.811  1.00  0.00    -0.017 A
ATOM      3  C   UNL     1      -7.638  79.554  82.338  1.00  0.00     0.098 A
ATOM      4  C   UNL     1      -7.360  79.819  81.009  1.00  0.00     0.110 A
ATOM      5  S   UNL     1      -8.899  80.300  80.380  1.00  0.00    -0.122 S
ATOM      6  C   UNL     1      -9.877  80.111  81.848  1.00  0.00     0.011 A
BRANCH   3   7
ATOM      7  C   UNL     1      -6.585  79.101  83.249  1.00  0.00     0.341 C
ATOM      8  O   UNL     1      -6.847  78.310  84.136  1.00  0.00    -0.246 OA
BRANCH   7   9
ATOM      9  O   UNL     1      -5.325  79.561  83.106  1.00  0.00    -0.465 OA
ATOM     10  C   UNL     1      -4.376  79.221  84.151  1.00  0.00     0.282 C
ENDBRANCH   7   9
ENDBRANCH   3   7
BRANCH   4  11
ATOM     11  N   UNL     1      -6.147  79.728  80.347  1.00  0.00    -0.311 N
ATOM     12  C   UNL     1      -5.966  78.786  79.401  1.00  0.00     0.276 C
ATOM     13  H   UNL     1      -5.429  80.343  80.563  1.00  0.00     0.171 HD
ATOM     14  O   UNL     1      -6.866  78.015  79.129  1.00  0.00    -0.267 OA
BRANCH  12  15
ATOM     15  C   UNL     1      -4.669  78.688  78.692  1.00  0.00     0.146 A
ATOM     16  N   UNL     1      -3.530  78.842  79.361  1.00  0.00    -0.248 NA
ATOM     17  C   UNL     1      -4.639  78.435  77.320  1.00  0.00     0.145 A
ATOM     18  C   UNL     1      -2.378  78.755  78.727  1.00  0.00     0.132 A
ATOM     19  N   UNL     1      -3.480  78.349  76.693  1.00  0.00    -0.261 NA
ATOM     20  C   UNL     1      -2.351  78.503  77.363  1.00  0.00     0.131 A
ENDBRANCH  12  15
ENDBRANCH   4  11
BRANCH   6  21
ATOM     21  C   UNL     1     -11.362  80.316  81.951  1.00  0.00     0.047 C
BRANCH  21  22
ATOM     22  C   UNL     1     -12.033  79.154  81.196  1.00  0.00     0.006 CG0
ATOM     23  G   UNL     1     -11.706  79.300  79.705  1.00  0.00     0.000 G0
ENDBRANCH  21  22
ENDBRANCH   6  21
ENDBRANCH   1   2
BRANCH   1  24
ATOM     24  C   UNL     1      -8.815  78.225  84.837  1.00  0.00     0.005 C
BRANCH  24  25
ATOM     25  C   UNL     1      -7.335  78.009  84.579  1.00  0.00     0.000 C
BRANCH  25  26
ATOM     26  C   UNL     1      -6.437  78.534  85.679  1.00  0.00     0.000 CG0
ATOM     27  G   UNL     1      -7.017  77.971  86.982  1.00  0.00     0.000 G0
ENDBRANCH  25  26
ENDBRANCH  24  25
ENDBRANCH   1  24
TORSDOF 4
ENDMDL
</pre>
<p>However, vina 1.2.5 gave another score for the same pose</p>
<pre line="1" lang="python">
AutoDock Vina v1.2.5
#################################################################
# If you used AutoDock Vina in your work, please cite:          #
#                                                               #
# J. Eberhardt, D. Santos-Martins, A. F. Tillack, and S. Forli  #
# AutoDock Vina 1.2.0: New Docking Methods, Expanded Force      #
# Field, and Python Bindings, J. Chem. Inf. Model. (2021)       #
# DOI 10.1021/acs.jcim.1c00203                                  #
#                                                               #
# O. Trott, A. J. Olson,                                        #
# AutoDock Vina: improving the speed and accuracy of docking    #
# with a new scoring function, efficient optimization and       #
# multithreading, J. Comp. Chem. (2010)                         #
# DOI 10.1002/jcc.21334                                         #
#                                                               #
# Please see https://github.com/ccsb-scripps/AutoDock-Vina for  #
# more information.                                             #
#################################################################

Scoring function : vina
Rigid receptor: 1udt_prot.pdbqt
Ligand: ZINC004423901.pdbqt
Grid center: X 1.548 Y 68.184 Z 83.831
Grid size  : X 30 Y 30 Z 30
Grid space : 0.375
Exhaustiveness: 8
CPU: 0
Verbosity: 2

Computing Vina grid ... done.
Estimated Free Energy of Binding   : -1.249 (kcal/mol) [=(1)+(2)+(3)-(4)]
(1) Final Intermolecular Energy    : -1.980 (kcal/mol)
    Ligand - Receptor              : -1.980 (kcal/mol)
    Ligand - Flex side chains      : 0.000 (kcal/mol)
(2) Final Total Internal Energy    : 20.086 (kcal/mol)
    Ligand                         : 20.086 (kcal/mol)
    Flex   - Receptor              : 0.000 (kcal/mol)
    Flex   - Flex side chains      : 0.000 (kcal/mol)
(3) Torsional Free Energy          : 0.730 (kcal/mol)
(4) Unbound System's Energy        : 20.086 (kcal/mol)
</pre>

**Comment by pkuyyj** [comment]
Hi Dr. Xiao,
Thank you for reporting. We have noticed this situation and in Uni-Dock, the code actually takes the most negative affinity as baseline to calculate intramolecular score, whereas Vina 1.2.5 takes the first pose as baseline and sometimes very positive score can take place. Maybe it's a tradeoff and we choose to have very negative, instead of very positive. Indeed, they might both be cause by incorrect ligand input. In this case, MODEL 1 has clashes.
The code are as follows:
```cpp
    poses.sort();
    // probably for bug very negative score
    m_model_gpu[l].set(poses[0].c);
```
Compared to https://github.com/ccsb-scripps/AutoDock-Vina/pull/81/commits/61df1f566bb02ec9100fe45a09ae435439e8c827
If you want us to reproduce this case, please provide us the receptor.

**Comment by gkxiao** [comment]
I know what happened. Unidock could not recognize atom G which allow Vina to sample the conformer of the macrocycle. If the input pdbqt file includes the atom of G, Unidock will give a   unexpected result. The solution is to keep the macrocycle rigid.
