### ISSUE TITLE
target_compile_features no known features for CXX compiler

### ISSUE THREAD

**Issue by AquifersBSIM** [dptech-corp/Uni-Dock#126]
### Describe the bug

Hi, I tried to install unidock and currently I am stuck at:

cmake -B build

after, inputting the command above, the following errors keep appearing. Can anybody help me with this?  
CMake Error at build/_deps/boost-src/libs/atomic/CMakeLists.txt:89 (target_compile_features):
  target_compile_features no known features for CXX compiler

  "GNU"

  version 12.2.0.

CMake Error at build/_deps/boost-src/libs/chrono/CMakeLists.txt:39 (target_compile_features):
  target_compile_features no known features for CXX compiler

  "GNU"

  version 12.2.0.

CMake Error at build/_deps/boost-src/libs/program_options/CMakeLists.txt:46 (target_compile_features):
  target_compile_features no known features for CXX compiler

  "GNU"

  version 12.2.0.

CMake Error at build/_deps/boost-src/libs/thread/CMakeLists.txt:83 (target_compile_features):
  target_compile_features no known features for CXX compiler

  "GNU"

  version 12.2.0.

**Comment by caic99** [comment]
Hi @AquifersBSIM ,
Please remove ./build and try again. What's your CMake version?

**Comment by AquifersBSIM** [comment]
hi, thank you for your reply :D. do i just "rm build"? My CMake version is "cmake version 3.29.2"

**Comment by caic99** [comment]
> hi @caic99, thank you for your reply :D. do i just "rm build"?

@AquifersBSIM Yes

> ml gcc/12.2.0 ml cuda/11.7.0 ml boost/1.81.0 ml cmake/3.24.3

That looks fine... If there are still problems, would you attach CMakeError.log (plz see the message after configuring fails).

**Comment by AquifersBSIM** [comment]
> > hi @caic99, thank you for your reply :D. do i just "rm build"?
> 
> @AquifersBSIM Yes
> 
> > ml gcc/12.2.0 ml cuda/11.7.0 ml boost/1.81.0 ml cmake/3.24.3
> 
> That looks fine... If there are still problems, would you attach CMakeError.log (plz see the message after configuring fails).

Hi @caic99, so far there is not much problem for now :D. Thank you so much for your replies. Can I ask, do I have to run the following command:

cmake --install build

**Comment by caic99** [comment]
> Hi @caic99, so far there is not much problem for now :D. Thank you so much for your replies. 

No problem, and thank you for trying out Uni-Dock.

> cmake --install build

It is optional. You'll either indicate the path to executable e.g. `./build/unidock`, or add the directory to $PATH.

**Comment by AquifersBSIM** [comment]
> > Hi @caic99, so far there is not much problem for now :D. Thank you so much for your replies.
> 
> No problem, and thank you for trying out Uni-Dock.
> 
> > cmake --install build
> 
> It is optional. You'll either indicate the path to executable e.g. `./build/unidock`, or add the directory to $PATH.

I see @caic99 , thank you so much again for replying and helping.
