### ISSUE TITLE
how to use muti gpus or choice the gpu that i want to use?

### ISSUE THREAD

**Issue by mapengsen** [dptech-corp/Uni-Dock#15]
how to use muti gpus or choice the gpu that i want to use?

**Comment by caic99** [comment]
Hi @mapengsen ,
Please set environment variable [CUDA_VISIBLE_DEVICES](https://developer.nvidia.com/blog/cuda-pro-tip-control-gpu-visibility-cuda_visible_devices/) before running `unidock`, e.g. `CUDA_VISIBLE_DEVICES=2 unidock <params>`. Please note that one `unidock` process does not support more than one GPU.
