### ISSUE TITLE
Can't find `unidock_ad4` after compiling from sources by `cmake`

### ISSUE THREAD

**Issue by yanze039** [dptech-corp/Uni-Dock#27]
Hi,

I am a bit confused that the README file said "Executable unidock supports vina and vinardo scoring functions, and unidock_ad4 supports ad4 scoring function."

But after I compiled from sources by `cmake`, only `unidock` exists not `unidock_ad4 `.

**Comment by caic99** [comment]
Hi @Dead-fisher ,
Sorry about the inconvenience. I'll fix it.

**Comment by caic99** [comment]
@YNYuan Would you update the status of this bug, and check if the linked PR is necessary? Thanks.

**Comment by dp-yuanyn** [comment]
@yanze039 @caic99 From [v1.1.1](https://github.com/dptech-corp/Uni-Dock/releases/tag/1.1.1), ```unidock``` has supported *ad4* scoring function (need to create maps first, [see](https://github.com/dptech-corp/Uni-Dock/blob/main/unidock/README.md?plain=1#L83)) and ```unidock_ad4``` has been deprecated.
