### ISSUE TITLE
Version still marked as 0.1.0 in the 1.0.0 release

### ISSUE THREAD

**Issue by james-vincent** [dptech-corp/Uni-Dock#41]
$ more CMakeLists.txt 
cmake_minimum_required(VERSION 3.16)
project(
	Uni-Dock
	VERSION 0.1.0
	DESCRIPTION "GPU-Accelerated Docking with 1000-fold speedup"
	HOMEPAGE_URL "https://github.com/dptech-corp/Uni-Dock"
	LANGUAGES CXX CUDA
)

**Comment by dp-yuanyn** [comment]
@james-vincent From [v1.1.0](https://github.com/dptech-corp/Uni-Dock/releases/tag/1.1.0), the version marked in Uni-Dock is correct.
