### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by dinu09** [dptech-corp/Uni-Dock#42]
I am having difficulty installing. I tried all the methods mentioned here. but none of them is working. I am using CentOS. 
I installed dependencies and cuda toolkit using conda .
1. Cloned from github repo but when I tried to execute cmake command, i got an error saying no folder build found. I want to know if I am missing something here. 
2. I tried to use conda to install Uni-dock using "**_conda install -c https://conda.mlops.dp.tech/caic -c conda-forge unidock_**" but again got an error "**_conda.core.prefix_data:_load_single_record(216): Ignoring malformed prefix record at: home/miniconda3/conda-meta/unidock-1.0.0-5_5.json_**"
3. Then i tried downloading "unidock-1.0.0-5_5.tar.bz2" file and run "conda install -c conda-forge unidock-1.0.0-5_5.tar.bz2" command. the command ran without errors but when I try to execute "unidock --help", I get an error unknown command. 

I am new to this. So, it will be great if someone can help. thanks!

**Comment by caic99** [comment]
Hi @dinu09 ,
I'm glad to help, and would you provide us the detailed command and output log in step 1 ? Thanks.

**Comment by dinu09** [comment]
Thanks @caic99. 

When I execute the cmake command, this is the error I got.
CMake Error: The source directory "/home/users/dinesh/Uni-Dock/build" does not exist.
Specify --help for usage, or press the help button on the CMake GUI

**Comment by caic99** [comment]
> Thanks @caic99.
> 
> When I execute the cmake command, this is the error I got. CMake Error: The source directory "/home/users/dinesh/Uni-Dock/build" does not exist. Specify --help for usage, or press the help button on the CMake GUI

@dinu09 Please also provide your input command

**Comment by dinu09** [comment]
cmake -B build

**Comment by caic99** [comment]
> cmake -B build

@dinu09 
Please enter the `unidock` subdirectory first. We will make the installation step more clear in our docs.

**Comment by dinu09** [comment]
@caic99 I entered unidock subdirectory and executed the **_cmake -B build_** command. 

CMake Error: The source directory "/home/users/dinesh/Uni-Dock/unidock/build" does not exist.

**Comment by caic99** [comment]
@dinu09 The command you used looks correct for me... Please try another approach: 
```bash
mkdir build
cd build
cmake ..
```

**Comment by dinu09** [comment]
@caic99 i think this issue is solved. i have other issues. I will check them out. Thank you for your help!!

**Comment by caic99** [comment]
> @caic99 after **cmake ..** should I use **cmake --build build -j4**?

@dinu09 Yes, please go ahead if the configuration succeed.
