### ISSUE TITLE
can

### ISSUE THREAD

**Issue by zengdashi** [dptech-corp/Uni-Dock#50]
can uni-dock generate 3d model for ligand using a 2d structure ?

**Comment by zhengh96** [comment]
Unfortunately, Uni-Dock does not generate 3D models for ligands using a 2D structure. Uni-Dock only samples the user-defined rotatable torsions to change conformations. You would need to generate the 3D conformations of your 2D molecule(s) before using Uni-Dock. Tools like RDKit and OpenBabel can be helpful for this purpose.

**Comment by zengdashi** [comment]
Thanks for your answer!
