### ISSUE TITLE
License

### ISSUE THREAD

**Issue by RaulFD-creator** [dptech-corp/Uni-Dock#51]
Hi, 

I am interested in integrating Uni-Dock in a docking workflow, but I wanted to check the license to see whether it is compatible with commercial usage. I haven't been able to find the license in the GitHub repo and wanted to check with you what the terms are.

Thanks beforehand!

**Comment by caic99** [comment]
Hi @RaulFD-creator ,
Uni-Dock is released under LGPL license. Please check the LICENSE file under subdirectory.

**Comment by RaulFD-creator** [comment]
Hi @caic99, thank you so much! I hadn't seen it, sorry for the inconvenience.
