### ISSUE TITLE
ERROR：Empty ligland list

### ISSUE THREAD

**Issue by Ljs1016** [dptech-corp/Uni-Dock#6]
My ligands.index have some records, but when I run the command
"./unidock --receptor Uni-Dock/example/screening_test/indata/def.pdbqt --ligand_index def_ligands.index --center_x -36.01 --center_y 25.63 --center_z 67.49 --size_x 17.20 --size_y 14.38 --size_z 12.24 --scoring vinardo --refine_step 3 --num_modes 1 --seed 5 --search_mode fast --dir results/def-fast "
Then will have some erros “ERROR：Empty ligland list”

**Comment by pkuyyj** [comment]
Please check your ligand file and make sure the paths are correct. If ligand parsing fails, this error can happen.

**Comment by Zehui7Zhou** [comment]
I also came across this error "ERROR：Empty ligland list" when running the example codes:

cp config_def.json config.json
python run_dock.py

**Comment by pkuyyj** [comment]
The global memory of the GPU should be larger than about 8GB, otherwise the ligands cannot be processed.
