### ISSUE TITLE
Please specify what the maximum number of ligand torsions is in the documentation.

### ISSUE THREAD

**Issue by jpmfc6** [dptech-corp/Uni-Dock#60]
Hi Uni-Dock Team,

    I've recently been using Uni-Dock for molecular docking and encountered an error when working with larger ligands. Specifically, I received an error message suggesting that my ligand exceeded the maximum torsion count, though I couldn't find a documented torsion limit in the Uni-Dock materials.

    For context, I'm aware that AutoDock 4 has a torsion limit of 32, and AutoDock-GPU has a limit of 58. In your publication, you mentioned docking ligands with up to 50 atoms, which might imply a similar limitation. Could you please clarify if there is a specific torsion or atom count limit for ligands in Uni-Dock? Including this information in the documentation would be extremely helpful for users in understanding the tool's capabilities and limitations.

    For reference, the ligand that caused the issue in my case has 60 torsions. This number and even more are handled by Vina 1.2.

    I appreciate your work on this promising tool and look forward to any updates or information you can provide.

    Thank you!

**Comment by ysyecust** [comment]
>     Hi Uni-Dock Team,
> 
> 
> 
>     I've recently been using Uni-Dock for molecular docking and encountered an error when working with larger ligands. Specifically, I received an error message suggesting that my ligand exceeded the maximum torsion count, though I couldn't find a documented torsion limit in the Uni-Dock materials.
> 
> 
> 
>     For context, I'm aware that AutoDock 4 has a torsion limit of 32, and AutoDock-GPU has a limit of 58. In your publication, you mentioned docking ligands with up to 50 atoms, which might imply a similar limitation. Could you please clarify if there is a specific torsion or atom count limit for ligands in Uni-Dock? Including this information in the documentation would be extremely helpful for users in understanding the tool's capabilities and limitations.
> 
> 
> 
>     For reference, the ligand that caused the issue in my case has 60 torsions. This number and even more are handled by Vina 1.2.
> 
> 
> 
>     I appreciate your work on this promising tool and look forward to any updates or information you can provide.
> 
> 
> 
>     Thank you!

Thank you for your inquiry. In the current version, the maximum atomic number is 300 and the maximum tosion number is 48. In later versions, we will further expand the scope of support.
