### ISSUE TITLE
Internal error occurred while running Uni-Dock using ad4 scoring function

### ISSUE THREAD

**Issue by dp-yuanyn** [dptech-corp/Uni-Dock#82]
### Describe the bug

![20240301-204856](https://github.com/dptech-corp/Uni-Dock/assets/139571209/f2d1f234-f89e-42f3-84b5-dc2d2f66b27b)

### To Reproduce

Here are the input files and running command (in ***run.sh***):

[failed_ad4.zip](https://github.com/dptech-corp/Uni-Dock/files/14461266/failed_hbond_ad4.zip)

### Environment

CUDA: 12.0.0
GPU: T4
Version: v1.1.0

**Comment by ysyecust** [comment]
fixed in https://github.com/dptech-corp/Uni-Dock/commit/cb2939e78d4e5c936f1be84b8045336c6d71fcf0
