### ISSUE TITLE
Feature Request: Separate ./unidock and ./unidock_tools as 2 repo

### ISSUE THREAD

**Issue by RuikangSun** [dptech-corp/Uni-Dock#84]
./unidock and ./unidock_tools are 2 different programs that have different functions and different licenses. Is it a better idea to separate ./unidock and ./unidock_tools as 2 repo?

**Comment by zhengh96** [comment]
Thank you for your suggestion. 

We understand that they are different programs with different functions and licenses. However, at the moment, Uni-Dock Tools is required to fully utilize the features available in Uni-Dock, such as using SDF and PDB formats for ligands and receptors.

Additionally, we plan to showcase a series of Uni-Dock usage methods under the Uni-Dock Tools repo, making it more accessible for users to see and learn from. Therefore, we have decided to keep the two programs in one repo for the time being.

We DO have plans for building a more user-friendly interface for Uni-Dock in the future. And when the time is appropriate, we will consider splitting the repos as you suggested. 

We appreciate your understanding and contribution to the project!
