### ISSUE TITLE
Potential array index out of range.

### ISSUE THREAD

**Issue by wzf03** [dptech-corp/Uni-Dock#85]
https://github.com/dptech-corp/Uni-Dock/blob/785d547bbfe81cbadfe84778df4f5566f0976df7/unidock/src/main/simulation_container.h#L211

**Comment by ysyecust** [comment]
Hi @prabindh, how do you think this problem should be solved?https://github.com/dptech-corp/Uni-Dock/blob/785d547bbfe81cbadfe84778df4f5566f0976df7/unidock/src/main/simulation_container.h#L211
