### ISSUE TITLE
cmake -B build -D FETCH_BOOST=ON  does not fetch boost

### ISSUE THREAD

**Issue by james-vincent** [dptech-corp/Uni-Dock#93]
### Describe the bug

Using cmake build process, boost fails to download/build:

This command:
cd Uni-Dock-1.1.0/unidock
cmake -B build -D FETCH_BOOST=ON

produces:

CMake Error at /build/x86_64-linux/cmake/3.22.2/cmake_extlib/cmake-3.22.2-tvg7/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Boost (missing: Boost_INCLUDE_DIR system thread
  serialization filesystem program_options timer) (Required is at least
  version "1.72")
Call Stack (most recent call first):
  /build/x86_64-linux/cmake/3.22.2/cmake_extlib/cmake-3.22.2-tvg7/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /build/x86_64-linux/cmake/3.22.2/cmake_extlib/cmake-3.22.2-tvg7/share/cmake-3.22/Modules/FindBoost.cmake:2375 (find_package_handle_standard_args)
  CMakeLists.txt:42 (find_package)

**Comment by ysyecust** [comment]
Hi @james-vincent, It seems that the boost library was not downloaded correctly, can you show me the full cmake error log,   
The correct cmake output is like this  ”cmake -B build -D FETCH_BOOST=ON
-- The CXX compiler identification is GNU 11.4.0
-- The CUDA compiler identification is NVIDIA 12.2.140
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
CMAKE_CUDA_FLAGS_RELEASE updated for fast_math: -O3 -DNDEBUG --use_fast_math
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- Populating boost
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ysy/Uni-Dock/unidock/build/_deps/boost-subbuild
[ 11%] Creating directories for 'boost-populate'
[ 22%] Performing download step (download, verify and extract) for 'boost-populate'
-- Downloading...
   dst='/home/ysy/Uni-Dock/unidock/build/_deps/boost-subbuild/boost-populate-prefix/src/boost-1.84.0.tar.gz'
   timeout='none'
   inactivity timeout='none'
-- Using src='https://github.com/boostorg/boost/releases/download/boost-1.84.0/boost-1.84.0.tar.gz'
-- [download 0% complete]
-- [download 1% complete]
-- [download 2% complete]
-- [download 3% complete]
-- [download 4% complete]
-- [download 5% complete]
-- [download 6% complete]
-- [download 7% complete]
-- [download 8% complete]
-- [download 9% complete]
-- [download 10% complete]
-- [download 11% complete]
-- [download 12% complete]
-- [download 13% complete]
-- [download 14% complete]
-- [download 15% complete]
-- [download 16% complete]
-- [download 17% complete]
-- [download 18% complete]
-- [download 19% complete]
-- [download 20% complete]
-- [download 21% complete]
-- [download 22% complete]
-- [download 23% complete]
-- [download 24% complete]
-- [download 25% complete]
-- [download 26% complete]
-- [download 27% complete]
-- [download 28% complete]
-- [download 29% complete]
-- [download 30% complete]
-- [download 31% complete]
-- [download 32% complete]
-- [download 33% complete]
-- [download 34% complete]
-- [download 35% complete]
-- [download 36% complete]
-- [download 37% complete]
-- [download 38% complete]
-- [download 39% complete]
-- [download 40% complete]
-- [download 41% complete]
-- [download 42% complete]
-- [download 43% complete]
-- [download 44% complete]
-- [download 45% complete]
-- [download 46% complete]
-- [download 47% complete]
-- [download 48% complete]
-- [download 49% complete]
-- [download 50% complete]
-- [download 51% complete]
-- [download 52% complete]
-- [download 53% complete]
-- [download 54% complete]
-- [download 55% complete]
-- [download 56% complete]
-- [download 57% complete]
-- [download 58% complete]
-- [download 59% complete]
-- [download 60% complete]
-- [download 61% complete]
-- [download 62% complete]
-- [download 63% complete]
-- [download 64% complete]
-- [download 65% complete]
-- [download 66% complete]
-- [download 67% complete]
-- [download 68% complete]
-- [download 69% complete]
-- [download 70% complete]
-- [download 71% complete]
-- [download 72% complete]
-- [download 73% complete]
-- [download 74% complete]
-- [download 75% complete]
-- [download 76% complete]
-- [download 77% complete]
-- [download 78% complete]
-- [download 79% complete]
-- [download 80% complete]
-- [download 81% complete]
-- [download 82% complete]
-- [download 83% complete]
-- [download 84% complete]
-- [download 85% complete]
-- [download 86% complete]
-- [download 87% complete]
-- [download 88% complete]
-- [download 89% complete]
-- [download 90% complete]
-- [download 91% complete]
-- [download 92% complete]
-- [download 93% complete]
-- [download 94% complete]
-- [download 95% complete]
-- [download 96% complete]
-- [download 97% complete]
-- [download 98% complete]
-- [download 99% complete]
-- [download 100% complete]
-- Downloading... done
-- extracting...
     src='/home/ysy/Uni-Dock/unidock/build/_deps/boost-subbuild/boost-populate-prefix/src/boost-1.84.0.tar.gz'
     dst='/home/ysy/Uni-Dock/unidock/build/_deps/boost-src'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[ 33%] No update step for 'boost-populate'
[ 44%] No patch step for 'boost-populate'
[ 55%] No configure step for 'boost-populate'
[ 66%] No build step for 'boost-populate'
[ 77%] No install step for 'boost-populate'
[ 88%] No test step for 'boost-populate'
[100%] Completed 'boost-populate'
[100%] Built target boost-populate
-- Boost: Release build, static libraries, MPI OFF, Python OFF, testing OFF
-- Boost: libraries included: system;thread;serialization;filesystem;program_options;timer
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Performing Test BOOST_ATOMIC_TARGET_X86
-- Performing Test BOOST_ATOMIC_TARGET_X86 - Success
-- Performing Test BOOST_ATOMIC_COMPILER_HAS_SSE2
-- Performing Test BOOST_ATOMIC_COMPILER_HAS_SSE2 - Success
-- Performing Test BOOST_ATOMIC_COMPILER_HAS_SSE41
-- Performing Test BOOST_ATOMIC_COMPILER_HAS_SSE41 - Success
-- The C compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Performing Test BOOST_FILESYSTEM_HAS_INIT_PRIORITY
-- Performing Test BOOST_FILESYSTEM_HAS_INIT_PRIORITY - Success
-- Performing Test BOOST_FILESYSTEM_HAS_CXX20_ATOMIC_REF
-- Performing Test BOOST_FILESYSTEM_HAS_CXX20_ATOMIC_REF - Failed
-- Performing Test BOOST_FILESYSTEM_HAS_STAT_ST_BLKSIZE
-- Performing Test BOOST_FILESYSTEM_HAS_STAT_ST_BLKSIZE - Success
-- Performing Test BOOST_FILESYSTEM_HAS_STAT_ST_MTIM
-- Performing Test BOOST_FILESYSTEM_HAS_STAT_ST_MTIM - Success
-- Performing Test BOOST_FILESYSTEM_HAS_STAT_ST_MTIMENSEC
-- Performing Test BOOST_FILESYSTEM_HAS_STAT_ST_MTIMENSEC - Failed
-- Performing Test BOOST_FILESYSTEM_HAS_STAT_ST_MTIMESPEC
-- Performing Test BOOST_FILESYSTEM_HAS_STAT_ST_MTIMESPEC - Failed
-- Performing Test BOOST_FILESYSTEM_HAS_STAT_ST_BIRTHTIMENSEC
-- Performing Test BOOST_FILESYSTEM_HAS_STAT_ST_BIRTHTIMENSEC - Failed
-- Performing Test BOOST_FILESYSTEM_HAS_STAT_ST_BIRTHTIMESPEC
-- Performing Test BOOST_FILESYSTEM_HAS_STAT_ST_BIRTHTIMESPEC - Failed
-- Performing Test BOOST_FILESYSTEM_HAS_STATX
-- Performing Test BOOST_FILESYSTEM_HAS_STATX - Success
-- Performing Test BOOST_FILESYSTEM_HAS_FDOPENDIR_NOFOLLOW
-- Performing Test BOOST_FILESYSTEM_HAS_FDOPENDIR_NOFOLLOW - Success
-- Performing Test BOOST_FILESYSTEM_HAS_DIRENT_D_TYPE
-- Performing Test BOOST_FILESYSTEM_HAS_DIRENT_D_TYPE - Success
-- Performing Test BOOST_FILESYSTEM_HAS_POSIX_AT_APIS
-- Performing Test BOOST_FILESYSTEM_HAS_POSIX_AT_APIS - Success
-- Found the following ICU libraries:
--   data (required)
--   i18n (required)
--   uc (required)
-- Found ICU: /usr/include (found version "70.1")
-- Boost.Thread: threading API is pthread
-- Populating catch2
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ysy/Uni-Dock/unidock/build/_deps/catch2-subbuild
[ 11%] Creating directories for 'catch2-populate'
[ 22%] Performing download step (git clone) for 'catch2-populate'
Cloning into 'catch2-src'...
HEAD is now at 6e79e682 v3.4.0
[ 33%] Performing update step for 'catch2-populate'
[ 44%] No patch step for 'catch2-populate'
[ 55%] No configure step for 'catch2-populate'
[ 66%] No build step for 'catch2-populate'
[ 77%] No install step for 'catch2-populate'
[ 88%] No test step for 'catch2-populate'
[100%] Completed 'catch2-populate'
[100%] Built target catch2-populate
-- Performing Test HAVE_FLAG__ffile_prefix_map__home_ysy_Uni_Dock_unidock_build__deps_catch2_src__
-- Performing Test HAVE_FLAG__ffile_prefix_map__home_ysy_Uni_Dock_unidock_build__deps_catch2_src__ - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ysy/Uni-Dock/unidock/build“

**Comment by james-vincent** [comment]
Here is the cmake error log:


 $ more CMakeError.log
Performing C++ SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD failed with the following output:
Change Dir: /build/source/uni-dock/1.1.0/linux/Uni-Dock-1.1.0/unidock/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake -f Makefile cmTC_60ed2/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_60ed2.dir/build.make CMakeFiles/cmTC_60ed2.dir/build
gmake[1]: Entering directory `/nfs/build/source/uni-dock/1.1.0/linux/Uni-Dock-1.1.0/unidock/build/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_60ed2.dir/src.cxx.o
/programs/x86_64-linux/gcc/4.9.4/bin/c++ -DCMAKE_HAVE_LIBC_PTHREAD  -std=gnu++14 -o CMakeFiles/cmTC_60ed2.dir/src.cxx.o -c /build/source/uni-dock/1.1.0/linux/Uni-Dock-1.1.0/unidock/build/CMakeFiles/CMakeTmp/src.cxx
Linking CXX executable cmTC_60ed2
/nfs/build/x86_64-linux/cmake/3.22.2/cmake_extlib/cmake-3.22.2-tvg7/bin/cmake -E cmake_link_script CMakeFiles/cmTC_60ed2.dir/link.txt --verbose=1
/programs/x86_64-linux/gcc/4.9.4/bin/c++ CMakeFiles/cmTC_60ed2.dir/src.cxx.o -o cmTC_60ed2
CMakeFiles/cmTC_60ed2.dir/src.cxx.o: In function `main':
src.cxx:(.text+0x2d): undefined reference to `pthread_create'
src.cxx:(.text+0x39): undefined reference to `pthread_detach'
src.cxx:(.text+0x45): undefined reference to `pthread_cancel'
src.cxx:(.text+0x56): undefined reference to `pthread_join'
src.cxx:(.text+0x6a): undefined reference to `pthread_atfork'
collect2: error: ld returned 1 exit status
gmake[1]: *** [cmTC_60ed2] Error 1
gmake[1]: Leaving directory `/nfs/build/source/uni-dock/1.1.0/linux/Uni-Dock-1.1.0/unidock/build/CMakeFiles/CMakeTmp'
gmake: *** [cmTC_60ed2/fast] Error 2




James Vincent, PhD
Bioinformatics Software Curator
Dept. of BCMP, Harvard Medical School
— BioGrids.org --

**Comment by ysyecust** [comment]
@james-vincent  You can add ```find_package(Threads)``` in CMakeLists.txt at line 61https://github.com/dptech-corp/Uni-Dock/blob/883671c330ceb9ee3cef4ca167bb12caa156ad43/unidock/CMakeLists.txt#L61, If that solves your problem I will update this part of the CMakeLists.txt

**Comment by james-vincent** [comment]
Thanks for the update. I was using the source tarball for version 1.1. It seems the CMakeLists file is different in that source tarball than what is now peresent in the repo itself. So, I cloned the repo instead. This worked finding boost with no further changes.

However, compilation fails finding some boost include files. Do I need to manually set BOOST_INCUDE_DIR or something similar?


-- Build files have been written to: /build/source/uni-dock/1.1.0/linux/Uni-Dock/unidock/build
[  0%] Building CXX object _deps/boost-build/libs/atomic/CMakeFiles/boost_atomic.dir/src/lock_pool.cpp.o
[  0%] Building CXX object CMakeFiles/lib.dir/src/lib/ad4cache.cpp.o
[  2%] Building CUDA object CMakeFiles/cuda.dir/src/cuda/monte_carlo.cu.o
[  2%] Building CXX object _deps/boost-build/libs/timer/CMakeFiles/boost_timer.dir/src/auto_timers_construction.cpp.o
In file included from /build/source/uni-dock/1.1.0/linux/Uni-Dock/unidock/src/lib/ad4cache.cpp:23:
/build/source/uni-dock/1.1.0/linux/Uni-Dock/unidock/src/lib/ad4cache.h:31:10: fatal error: boost/serialization/split_member.hpp: No such file or directory
   31 | #include <boost/serialization/split_member.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.




James Vincent, PhD
Bioinformatics Software Curator
Dept. of BCMP, Harvard Medical School
— BioGrids.org --
